#!/bin/bash

if [[ -e /etc/debian_version && `which apt-get` ]] &>/dev/null ; then
    if [[ -e /etc/lsb-release ]] ; then
        dist=`grep DISTRIB_ID /etc/lsb-release | awk -F = '{print $2}'`
        release=`grep DISTRIB_CODENAME /etc/lsb-release | awk -F = '{print $2}'`
    else
        dist="Debian"
        release=`cat /etc/debian_version`
    fi
    cache_time_ref=/var/cache/apt/pkgcache.bin
    delta=0

    # Only try to manually update the cache, if cron-apt is not installed.
    if [[ `dpkg-query -W -f='${Status}\n' cron-apt` != "install ok installed" ]] &>/dev/null ; then
        cache_time_ref=/var/cache/apt/pkgcache.bin
        now=`date +%s`
        mtime=`stat -c %Y $cache_time_ref`
        delta=$((now - mtime))

        if [[ $delta -gt 28800 ]] ; then
            /usr/bin/apt-get update &>/dev/null
            if [ $? -eq 0 ]; then
                /usr/bin/touch $cache_time_ref
            fi
            delta=0
        fi
    fi

    echo "<<<apt>>>"
    echo $delta
    echo $dist
    echo $release
    if [[ $dist == "Ubuntu" ]] ; then
    # In Ubuntu's apt-get the number of output fields varies, so we need awk to search for repo information...
        waitmax 25 /usr/bin/apt-get -o Debug::NoLocking=yes -s dist-upgrade -y |\
		awk -v dist="$dist" '/^Inst/{\
			match($0,dist":[a-z,A-Z,0-9./-]*");\
			distinfo = substr($0,RSTART,RLENGTH);\
			print $2 " " distinfo;\
		 }' || echo "timeout_apt_get)"
    else
        waitmax 25 /usr/bin/apt-get -o Debug::NoLocking=yes -s dist-upgrade -y | awk '/^Inst/ { print $2 " " $5 }' || echo "timeout_apt_get)"
    fi
fi
